Warning: no access to tty (Bad file descriptor).
Thus no job control in this shell.
Mon Nov  6 12:41:37 GMT 2023
/home1/datahome/mdemol/historical_analysis/launch/jlab.py:29: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  elif dashinfo is not "0":
/home1/datahome/mdemol/historical_analysis/launch/jlab.py:32: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if dashinfo is not "0":
[I 2023-11-06 12:41:44.821 ServerApp] Package jupyterlab took 0.0000s to import
[I 2023-11-06 12:41:45.016 ServerApp] Package jupyter_lsp took 0.1942s to import
[W 2023-11-06 12:41:45.016 ServerApp] A `_jupyter_server_extension_points` function was not found in jupyter_lsp. Instead, a `_jupyter_server_extension_paths` function was found and will be used for now. This function name will be deprecated in future releases of Jupyter Server.
[I 2023-11-06 12:41:45.141 ServerApp] Package jupyter_server_terminals took 0.1246s to import
[I 2023-11-06 12:41:45.141 ServerApp] Package notebook took 0.0000s to import
[I 2023-11-06 12:41:45.143 ServerApp] Package notebook_shim took 0.0000s to import
[W 2023-11-06 12:41:45.143 ServerApp] A `_jupyter_server_extension_points` function was not found in notebook_shim. Instead, a `_jupyter_server_extension_paths` function was found and will be used for now. This function name will be deprecated in future releases of Jupyter Server.
[I 2023-11-06 12:41:48.100 ServerApp] Package panel.io.jupyter_server_extension took 2.9365s to import
[I 2023-11-06 12:41:48.100 ServerApp] jupyter_lsp | extension was successfully linked.
[I 2023-11-06 12:41:48.105 ServerApp] jupyter_server_terminals | extension was successfully linked.
[I 2023-11-06 12:41:48.110 ServerApp] jupyterlab | extension was successfully linked.
[W 2023-11-06 12:41:48.125 JupyterNotebookApp] 'password' has moved from NotebookApp to ServerApp. This config will be passed to ServerApp. Be sure to update your config before our next release.
[W 2023-11-06 12:41:48.128 ServerApp] ServerApp.password config is deprecated in 2.0. Use PasswordIdentityProvider.hashed_password.
[I 2023-11-06 12:41:48.128 ServerApp] notebook | extension was successfully linked.
[I 2023-11-06 12:41:50.733 ServerApp] notebook_shim | extension was successfully linked.
[I 2023-11-06 12:41:50.733 ServerApp] panel.io.jupyter_server_extension | extension was successfully linked.
[I 2023-11-06 12:41:50.913 ServerApp] notebook_shim | extension was successfully loaded.
[I 2023-11-06 12:41:50.916 ServerApp] jupyter_lsp | extension was successfully loaded.
[I 2023-11-06 12:41:50.918 ServerApp] jupyter_server_terminals | extension was successfully loaded.
[I 2023-11-06 12:41:50.921 LabApp] JupyterLab extension loaded from /home1/datahome/mdemol/.miniconda3/envs/histenv2/lib/python3.9/site-packages/jupyterlab
[I 2023-11-06 12:41:50.921 LabApp] JupyterLab application directory is /home1/datahome/mdemol/.miniconda3/envs/histenv2/share/jupyter/lab
[I 2023-11-06 12:41:50.921 LabApp] Extension Manager is 'pypi'.
[I 2023-11-06 12:41:50.925 ServerApp] jupyterlab | extension was successfully loaded.
[I 2023-11-06 12:41:50.928 ServerApp] notebook | extension was successfully loaded.
[I 2023-11-06 12:41:50.929 ServerApp] panel.io.jupyter_server_extension | extension was successfully loaded.
[I 2023-11-06 12:41:50.929 ServerApp] Serving notebooks from local directory: /home1/datahome/mdemol
[I 2023-11-06 12:41:50.929 ServerApp] Jupyter Server 2.9.1 is running at:
[I 2023-11-06 12:41:50.929 ServerApp] http://r2i0n20:8877/lab
[I 2023-11-06 12:41:50.929 ServerApp]     http://127.0.0.1:8877/lab
[I 2023-11-06 12:41:50.929 ServerApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[I 2023-11-06 12:41:50.987 ServerApp] Skipped non-installed server(s): bash-language-server, dockerfile-language-server-nodejs, javascript-typescript-langserver, jedi-language-server, julia-language-server, pyright, python-language-server, python-lsp-server, r-languageserver, sql-language-server, texlab, typescript-language-server, unified-language-server, vscode-css-languageserver-bin, vscode-html-languageserver-bin, vscode-json-languageserver-bin, yaml-language-server
[W 2023-11-06 12:42:01.666 ServerApp] 404 GET /api/kernels/7407731e-172f-4835-9d72-8137ba85aed0?1699274521653 (10.148.1.145): Kernel does not exist: 7407731e-172f-4835-9d72-8137ba85aed0
[W 2023-11-06 12:42:01.666 ServerApp] wrote error: 'Kernel does not exist: 7407731e-172f-4835-9d72-8137ba85aed0'
    Traceback (most recent call last):
      File "/home1/datahome/mdemol/.miniconda3/envs/histenv2/lib/python3.9/site-packages/tornado/web.py", line 1786, in _execute
        result = await result
      File "/home1/datahome/mdemol/.miniconda3/envs/histenv2/lib/python3.9/site-packages/jupyter_server/services/kernels/handlers.py", line 75, in get
        model = await ensure_async(km.kernel_model(kernel_id))
      File "/home1/datahome/mdemol/.miniconda3/envs/histenv2/lib/python3.9/site-packages/jupyter_server/services/kernels/kernelmanager.py", line 500, in kernel_model
        self._check_kernel_id(kernel_id)
      File "/home1/datahome/mdemol/.miniconda3/envs/histenv2/lib/python3.9/site-packages/jupyter_server/services/kernels/kernelmanager.py", line 531, in _check_kernel_id
        raise web.HTTPError(404, "Kernel does not exist: %s" % kernel_id)
    tornado.web.HTTPError: HTTP 404: Not Found (Kernel does not exist: 7407731e-172f-4835-9d72-8137ba85aed0)
[W 2023-11-06 12:42:01.680 ServerApp] 404 GET /api/kernels/7407731e-172f-4835-9d72-8137ba85aed0?1699274521653 (561c211cf284414792903f89972ed90c@10.148.1.145) 14.38ms referer=http://localhost:8877/lab/tree/historical_analysis/1_zarr_coloc.ipynb
[W 2023-11-06 12:42:03.324 ServerApp] 404 GET /api/kernels/7407731e-172f-4835-9d72-8137ba85aed0/channels?session_id=94b10bb6-2bb9-40f4-ab6d-47e36264fe05 (10.148.1.145): Kernel does not exist: 7407731e-172f-4835-9d72-8137ba85aed0
[W 2023-11-06 12:42:03.506 ServerApp] 404 GET /api/kernels/7407731e-172f-4835-9d72-8137ba85aed0/channels?session_id=94b10bb6-2bb9-40f4-ab6d-47e36264fe05 (561c211cf284414792903f89972ed90c@10.148.1.145) 181.99ms referer=None
[W 2023-11-06 12:42:03.529 ServerApp] 404 GET /api/kernels/7407731e-172f-4835-9d72-8137ba85aed0?1699274523516 (10.148.1.145): Kernel does not exist: 7407731e-172f-4835-9d72-8137ba85aed0
[W 2023-11-06 12:42:03.529 ServerApp] wrote error: 'Kernel does not exist: 7407731e-172f-4835-9d72-8137ba85aed0'
    Traceback (most recent call last):
      File "/home1/datahome/mdemol/.miniconda3/envs/histenv2/lib/python3.9/site-packages/tornado/web.py", line 1786, in _execute
        result = await result
      File "/home1/datahome/mdemol/.miniconda3/envs/histenv2/lib/python3.9/site-packages/jupyter_server/services/kernels/handlers.py", line 75, in get
        model = await ensure_async(km.kernel_model(kernel_id))
      File "/home1/datahome/mdemol/.miniconda3/envs/histenv2/lib/python3.9/site-packages/jupyter_server/services/kernels/kernelmanager.py", line 500, in kernel_model
        self._check_kernel_id(kernel_id)
      File "/home1/datahome/mdemol/.miniconda3/envs/histenv2/lib/python3.9/site-packages/jupyter_server/services/kernels/kernelmanager.py", line 531, in _check_kernel_id
        raise web.HTTPError(404, "Kernel does not exist: %s" % kernel_id)
    tornado.web.HTTPError: HTTP 404: Not Found (Kernel does not exist: 7407731e-172f-4835-9d72-8137ba85aed0)
[W 2023-11-06 12:42:03.530 ServerApp] 404 GET /api/kernels/7407731e-172f-4835-9d72-8137ba85aed0?1699274523516 (561c211cf284414792903f89972ed90c@10.148.1.145) 1.29ms referer=http://localhost:8877/lab/tree/historical_analysis/1_zarr_coloc.ipynb
[W 2023-11-06 12:42:03.913 ServerApp] 404 GET /api/kernels/7407731e-172f-4835-9d72-8137ba85aed0/channels?session_id=94b10bb6-2bb9-40f4-ab6d-47e36264fe05 (10.148.1.145): Kernel does not exist: 7407731e-172f-4835-9d72-8137ba85aed0
[W 2023-11-06 12:42:03.914 ServerApp] 404 GET /api/kernels/7407731e-172f-4835-9d72-8137ba85aed0/channels?session_id=94b10bb6-2bb9-40f4-ab6d-47e36264fe05 (561c211cf284414792903f89972ed90c@10.148.1.145) 1.00ms referer=None
[W 2023-11-06 12:42:04.013 ServerApp] 404 GET /api/kernels/7407731e-172f-4835-9d72-8137ba85aed0?1699274524001 (10.148.1.145): Kernel does not exist: 7407731e-172f-4835-9d72-8137ba85aed0
[W 2023-11-06 12:42:04.014 ServerApp] wrote error: 'Kernel does not exist: 7407731e-172f-4835-9d72-8137ba85aed0'
    Traceback (most recent call last):
      File "/home1/datahome/mdemol/.miniconda3/envs/histenv2/lib/python3.9/site-packages/tornado/web.py", line 1786, in _execute
        result = await result
      File "/home1/datahome/mdemol/.miniconda3/envs/histenv2/lib/python3.9/site-packages/jupyter_server/services/kernels/handlers.py", line 75, in get
        model = await ensure_async(km.kernel_model(kernel_id))
      File "/home1/datahome/mdemol/.miniconda3/envs/histenv2/lib/python3.9/site-packages/jupyter_server/services/kernels/kernelmanager.py", line 500, in kernel_model
        self._check_kernel_id(kernel_id)
      File "/home1/datahome/mdemol/.miniconda3/envs/histenv2/lib/python3.9/site-packages/jupyter_server/services/kernels/kernelmanager.py", line 531, in _check_kernel_id
        raise web.HTTPError(404, "Kernel does not exist: %s" % kernel_id)
    tornado.web.HTTPError: HTTP 404: Not Found (Kernel does not exist: 7407731e-172f-4835-9d72-8137ba85aed0)
[W 2023-11-06 12:42:04.014 ServerApp] 404 GET /api/kernels/7407731e-172f-4835-9d72-8137ba85aed0?1699274524001 (561c211cf284414792903f89972ed90c@10.148.1.145) 0.89ms referer=http://localhost:8877/lab/tree/historical_analysis/1_zarr_coloc.ipynb
[W 2023-11-06 12:42:09.199 ServerApp] 404 GET /api/kernels/7407731e-172f-4835-9d72-8137ba85aed0/channels?session_id=94b10bb6-2bb9-40f4-ab6d-47e36264fe05 (10.148.1.145): Kernel does not exist: 7407731e-172f-4835-9d72-8137ba85aed0
[W 2023-11-06 12:42:09.201 ServerApp] 404 GET /api/kernels/7407731e-172f-4835-9d72-8137ba85aed0/channels?session_id=94b10bb6-2bb9-40f4-ab6d-47e36264fe05 (561c211cf284414792903f89972ed90c@10.148.1.145) 1.55ms referer=None
[W 2023-11-06 12:42:09.315 ServerApp] 404 GET /api/kernels/7407731e-172f-4835-9d72-8137ba85aed0?1699274529304 (10.148.1.145): Kernel does not exist: 7407731e-172f-4835-9d72-8137ba85aed0
[W 2023-11-06 12:42:09.315 ServerApp] wrote error: 'Kernel does not exist: 7407731e-172f-4835-9d72-8137ba85aed0'
    Traceback (most recent call last):
      File "/home1/datahome/mdemol/.miniconda3/envs/histenv2/lib/python3.9/site-packages/tornado/web.py", line 1786, in _execute
        result = await result
      File "/home1/datahome/mdemol/.miniconda3/envs/histenv2/lib/python3.9/site-packages/jupyter_server/services/kernels/handlers.py", line 75, in get
        model = await ensure_async(km.kernel_model(kernel_id))
      File "/home1/datahome/mdemol/.miniconda3/envs/histenv2/lib/python3.9/site-packages/jupyter_server/services/kernels/kernelmanager.py", line 500, in kernel_model
        self._check_kernel_id(kernel_id)
      File "/home1/datahome/mdemol/.miniconda3/envs/histenv2/lib/python3.9/site-packages/jupyter_server/services/kernels/kernelmanager.py", line 531, in _check_kernel_id
        raise web.HTTPError(404, "Kernel does not exist: %s" % kernel_id)
    tornado.web.HTTPError: HTTP 404: Not Found (Kernel does not exist: 7407731e-172f-4835-9d72-8137ba85aed0)
[W 2023-11-06 12:42:09.316 ServerApp] 404 GET /api/kernels/7407731e-172f-4835-9d72-8137ba85aed0?1699274529304 (561c211cf284414792903f89972ed90c@10.148.1.145) 0.99ms referer=http://localhost:8877/lab/tree/historical_analysis/1_zarr_coloc.ipynb
[W 2023-11-06 13:07:06.734 LabApp] Could not determine jupyterlab build status without nodejs
[I 2023-11-06 13:07:14.002 ServerApp] Kernel started: 4dc8e9b0-0bc0-4696-a961-620278fa266c
readline: /etc/inputrc: line 19: term: unknown variable name
[I 2023-11-06 13:07:21.421 ServerApp] Connecting to kernel 4dc8e9b0-0bc0-4696-a961-620278fa266c.
[I 2023-11-06 13:07:21.424 ServerApp] Connecting to kernel 4dc8e9b0-0bc0-4696-a961-620278fa266c.
[I 2023-11-06 13:07:21.426 ServerApp] Connecting to kernel 4dc8e9b0-0bc0-4696-a961-620278fa266c.
[I 2023-11-06 13:09:13.360 ServerApp] Saving file at /historical_analysis/1_zarr_coloc.ipynb
[I 2023-11-06 13:11:13.924 ServerApp] Saving file at /historical_analysis/1_zarr_coloc.ipynb
[I 2023-11-06 13:21:17.226 ServerApp] Saving file at /historical_analysis/1_zarr_coloc.ipynb
[I 2023-11-06 13:21:32.487 ServerApp] Starting buffering for 4dc8e9b0-0bc0-4696-a961-620278fa266c:d0b43241-1c9d-41a6-ba47-c5893c9189c2
[W 2023-11-06 13:21:33.858 LabApp] Could not determine jupyterlab build status without nodejs
[I 2023-11-06 13:21:33.926 ServerApp] Connecting to kernel 4dc8e9b0-0bc0-4696-a961-620278fa266c.
[I 2023-11-06 13:21:34.030 ServerApp] Starting buffering for 4dc8e9b0-0bc0-4696-a961-620278fa266c:7d69c543-88ac-49e3-9dec-630b8989f235
[I 2023-11-06 13:21:35.003 ServerApp] Connecting to kernel 4dc8e9b0-0bc0-4696-a961-620278fa266c.
[I 2023-11-06 13:22:28.158 ServerApp] Starting buffering for 4dc8e9b0-0bc0-4696-a961-620278fa266c:b1d8981e-f728-4ad7-837f-0f1331cb6256
[W 2023-11-06 13:22:29.449 LabApp] Could not determine jupyterlab build status without nodejs
[I 2023-11-06 13:22:29.520 ServerApp] Connecting to kernel 4dc8e9b0-0bc0-4696-a961-620278fa266c.
[I 2023-11-06 13:22:29.597 ServerApp] Starting buffering for 4dc8e9b0-0bc0-4696-a961-620278fa266c:4e836d71-ecda-4e76-826b-1153e41aaebe
[I 2023-11-06 13:22:30.314 ServerApp] Connecting to kernel 4dc8e9b0-0bc0-4696-a961-620278fa266c.
[I 2023-11-06 13:24:30.089 ServerApp] Saving file at /historical_analysis/1_zarr_coloc.ipynb
[I 2023-11-06 13:28:30.295 ServerApp] Saving file at /historical_analysis/1_zarr_coloc.ipynb
[I 2023-11-06 14:01:05.084 ServerApp] Starting buffering for 4dc8e9b0-0bc0-4696-a961-620278fa266c:e828afd6-5f3d-4860-afce-eb3569ec557a
[W 2023-11-06 14:01:06.444 LabApp] Could not determine jupyterlab build status without nodejs
[I 2023-11-06 14:01:06.494 ServerApp] Connecting to kernel 4dc8e9b0-0bc0-4696-a961-620278fa266c.
[I 2023-11-06 14:01:06.568 ServerApp] Starting buffering for 4dc8e9b0-0bc0-4696-a961-620278fa266c:1b08ede3-9053-45bd-93b2-fc1e92b323ce
[I 2023-11-06 14:01:07.483 ServerApp] Connecting to kernel 4dc8e9b0-0bc0-4696-a961-620278fa266c.
[I 2023-11-06 14:01:24.498 ServerApp] Starting buffering for 4dc8e9b0-0bc0-4696-a961-620278fa266c:4bf51d32-abdb-4a95-9252-d0e768eb1968
[W 2023-11-06 14:01:25.774 LabApp] Could not determine jupyterlab build status without nodejs
[I 2023-11-06 14:01:25.826 ServerApp] Connecting to kernel 4dc8e9b0-0bc0-4696-a961-620278fa266c.
[I 2023-11-06 14:01:25.916 ServerApp] Starting buffering for 4dc8e9b0-0bc0-4696-a961-620278fa266c:c3cbb544-d93f-4a36-8b82-5e54ccc6700b
[I 2023-11-06 14:01:26.461 ServerApp] Connecting to kernel 4dc8e9b0-0bc0-4696-a961-620278fa266c.
[I 2023-11-06 14:01:53.384 ServerApp] Starting buffering for 4dc8e9b0-0bc0-4696-a961-620278fa266c:646a5ccd-0c81-439a-ba74-aa66c05dd6a5
[W 2023-11-06 14:01:54.645 LabApp] Could not determine jupyterlab build status without nodejs
[I 2023-11-06 14:01:54.752 ServerApp] Connecting to kernel 4dc8e9b0-0bc0-4696-a961-620278fa266c.
[I 2023-11-06 14:01:54.820 ServerApp] Starting buffering for 4dc8e9b0-0bc0-4696-a961-620278fa266c:1430c492-64a2-4e32-b0a9-96cb1c2b4110
[I 2023-11-06 14:01:55.250 ServerApp] Connecting to kernel 4dc8e9b0-0bc0-4696-a961-620278fa266c.
[I 2023-11-06 14:02:09.979 ServerApp] Starting buffering for 4dc8e9b0-0bc0-4696-a961-620278fa266c:e88852ab-e899-4d28-9e35-820d7a65987d
[W 2023-11-06 14:02:11.269 LabApp] Could not determine jupyterlab build status without nodejs
[I 2023-11-06 14:02:11.319 ServerApp] Connecting to kernel 4dc8e9b0-0bc0-4696-a961-620278fa266c.
[I 2023-11-06 14:02:11.399 ServerApp] Starting buffering for 4dc8e9b0-0bc0-4696-a961-620278fa266c:743fdc80-c75a-4f8c-a8a2-961ba8bce1c3
[I 2023-11-06 14:02:11.932 ServerApp] Connecting to kernel 4dc8e9b0-0bc0-4696-a961-620278fa266c.
[I 2023-11-06 14:02:53.972 ServerApp] Starting buffering for 4dc8e9b0-0bc0-4696-a961-620278fa266c:2b26a24a-e34f-4947-b9ea-e8c9f5aeab5b
[W 2023-11-06 14:02:55.246 LabApp] Could not determine jupyterlab build status without nodejs
[I 2023-11-06 14:02:55.301 ServerApp] Connecting to kernel 4dc8e9b0-0bc0-4696-a961-620278fa266c.
[I 2023-11-06 14:02:55.395 ServerApp] Starting buffering for 4dc8e9b0-0bc0-4696-a961-620278fa266c:26ea7b54-7063-4c07-854c-86e2cc2aaf33
[I 2023-11-06 14:02:55.863 ServerApp] Connecting to kernel 4dc8e9b0-0bc0-4696-a961-620278fa266c.
[I 2023-11-06 14:02:57.888 ServerApp] Starting buffering for 4dc8e9b0-0bc0-4696-a961-620278fa266c:2133d839-6616-4f09-9086-828569fda172
[W 2023-11-06 14:02:59.171 LabApp] Could not determine jupyterlab build status without nodejs
[I 2023-11-06 14:02:59.216 ServerApp] Connecting to kernel 4dc8e9b0-0bc0-4696-a961-620278fa266c.
[I 2023-11-06 14:02:59.312 ServerApp] Starting buffering for 4dc8e9b0-0bc0-4696-a961-620278fa266c:56be5e13-385e-4aa8-89a4-0c04cc26fe42
[I 2023-11-06 14:02:59.742 ServerApp] Connecting to kernel 4dc8e9b0-0bc0-4696-a961-620278fa266c.
[I 2023-11-06 14:03:04.668 ServerApp] Starting buffering for 4dc8e9b0-0bc0-4696-a961-620278fa266c:0cd0c982-0edd-469b-96cc-50f718a38027
[W 2023-11-06 14:03:10.439 LabApp] Could not determine jupyterlab build status without nodejs
[I 2023-11-06 14:03:10.497 ServerApp] Connecting to kernel 4dc8e9b0-0bc0-4696-a961-620278fa266c.
[I 2023-11-06 14:03:10.558 ServerApp] Starting buffering for 4dc8e9b0-0bc0-4696-a961-620278fa266c:2d3dfcf4-62bb-4b54-bce1-1a7288ed97eb
[I 2023-11-06 14:03:11.028 ServerApp] Connecting to kernel 4dc8e9b0-0bc0-4696-a961-620278fa266c.
[I 2023-11-06 14:03:11.504 ServerApp] Starting buffering for 4dc8e9b0-0bc0-4696-a961-620278fa266c:607454d6-e6f3-4bf2-9d6e-63c30c189230
[W 2023-11-06 14:03:12.809 LabApp] Could not determine jupyterlab build status without nodejs
[I 2023-11-06 14:03:12.865 ServerApp] Connecting to kernel 4dc8e9b0-0bc0-4696-a961-620278fa266c.
[I 2023-11-06 14:03:12.927 ServerApp] Starting buffering for 4dc8e9b0-0bc0-4696-a961-620278fa266c:8bc839b8-d36c-4b54-b060-f907a32517fa
[I 2023-11-06 14:03:13.518 ServerApp] Connecting to kernel 4dc8e9b0-0bc0-4696-a961-620278fa266c.
[C 2023-11-06 14:03:41.128 ServerApp] received signal 15, stopping
Terminated
[I 2023-11-06 14:03:41.178 ServerApp] Shutting down 6 extensions
[I 2023-11-06 14:03:41.178 ServerApp] Shutting down 1 kernel
[I 2023-11-06 14:03:41.178 ServerApp] Kernel shutdown: 4dc8e9b0-0bc0-4696-a961-620278fa266c
[C 2023-11-06 14:03:43.156 ServerApp] received signal 15, stopping
[I 2023-11-06 14:03:43.156 ServerApp] Shutting down 6 extensions
[I 2023-11-06 14:03:43.157 ServerApp] Shutting down 1 kernel
[I 2023-11-06 14:03:43.157 ServerApp] Kernel shutdown: 4dc8e9b0-0bc0-4696-a961-620278fa266c
